export const LETTERS = [
  { letter: 'A', emoji: '🍎', word: 'Apple', color: '#FF6B8A', free: true },
  { letter: 'B', emoji: '🐝', word: 'Bee', color: '#FFB347', free: true },
  { letter: 'C', emoji: '🐱', word: 'Cat', color: '#4DAAFF', free: true },
  { letter: 'D', emoji: '🐕', word: 'Dog', color: '#B57BFF', free: true },
  { letter: 'E', emoji: '🥚', word: 'Egg', color: '#5DD87A', free: true },
  { letter: 'F', emoji: '🐸', word: 'Frog', color: '#FF6B8A', free: false },
  { letter: 'G', emoji: '🍇', word: 'Grapes', color: '#B57BFF', free: false },
  { letter: 'H', emoji: '🏠', word: 'House', color: '#FF9F43', free: false },
  { letter: 'I', emoji: '🍦', word: 'Ice Cream', color: '#4DAAFF', free: false },
  { letter: 'J', emoji: '🪼', word: 'Jellyfish', color: '#5DD87A', free: false },
  { letter: 'K', emoji: '🦘', word: 'Kangaroo', color: '#FF6B8A', free: false },
  { letter: 'L', emoji: '🦁', word: 'Lion', color: '#FFB347', free: false },
  { letter: 'M', emoji: '🐒', word: 'Monkey', color: '#B57BFF', free: false },
  { letter: 'N', emoji: '🌙', word: 'Night', color: '#4DAAFF', free: false },
  { letter: 'O', emoji: '🦉', word: 'Owl', color: '#FF9F43', free: false },
  { letter: 'P', emoji: '🐧', word: 'Penguin', color: '#5DD87A', free: false },
  { letter: 'Q', emoji: '👸', word: 'Queen', color: '#FF6B8A', free: false },
  { letter: 'R', emoji: '🌈', word: 'Rainbow', color: '#FFB347', free: false },
  { letter: 'S', emoji: '⭐', word: 'Star', color: '#B57BFF', free: false },
  { letter: 'T', emoji: '🐢', word: 'Turtle', color: '#4DAAFF', free: false },
  { letter: 'U', emoji: '☂️', word: 'Umbrella', color: '#FF9F43', free: false },
  { letter: 'V', emoji: '🌺', word: 'Violet', color: '#5DD87A', free: false },
  { letter: 'W', emoji: '🐳', word: 'Whale', color: '#FF6B8A', free: false },
  { letter: 'X', emoji: '🎻', word: 'Xylophone', color: '#B57BFF', free: false },
  { letter: 'Y', emoji: '🧶', word: 'Yarn', color: '#FFB347', free: false },
  { letter: 'Z', emoji: '🦓', word: 'Zebra', color: '#4DAAFF', free: false },
];

export const RHYMES = [
  {
    id: 1,
    icon: '🌟',
    title: 'Twinkle Twinkle',
    preview: 'Twinkle, twinkle, little star...',
    free: true,
    lines: [
      'Twinkle, twinkle, little star,',
      'How I wonder what you are!',
      'Up above the world so high,',
      'Like a diamond in the sky.',
      'Twinkle, twinkle, little star,',
      'How I wonder what you are!',
    ],
  },
  {
    id: 2,
    icon: '🐑',
    title: 'Baa Baa Black Sheep',
    preview: 'Baa baa black sheep, have you any wool?',
    free: true,
    lines: [
      'Baa baa black sheep, have you any wool?',
      'Yes sir, yes sir, three bags full!',
      'One for the master, one for the dame,',
      'And one for the little boy who lives down the lane.',
    ],
  },
  {
    id: 3,
    icon: '🌧️',
    title: 'Rain Rain Go Away',
    preview: 'Rain, rain, go away...',
    free: false,
    lines: [
      'Rain, rain, go away,',
      'Come again another day.',
      'Little children want to play,',
      'Rain, rain, go away!',
    ],
  },
  {
    id: 4,
    icon: '🥚',
    title: 'Humpty Dumpty',
    preview: 'Humpty Dumpty sat on a wall...',
    free: false,
    lines: [
      'Humpty Dumpty sat on a wall,',
      'Humpty Dumpty had a great fall.',
      "All the king's horses and all the king's men,",
      "Couldn't put Humpty together again.",
    ],
  },
  {
    id: 5,
    icon: '🐛',
    title: 'Incy Wincy Spider',
    preview: 'Incy Wincy Spider climbed up the waterspout...',
    free: false,
    lines: [
      'Incy Wincy Spider climbed up the waterspout.',
      'Down came the rain and washed the spider out.',
      'Out came the sunshine and dried up all the rain.',
      'And Incy Wincy Spider climbed up the spout again!',
    ],
  },
  {
    id: 6,
    icon: '🛶',
    title: 'Row Row Row Your Boat',
    preview: 'Row, row, row your boat...',
    free: false,
    lines: [
      'Row, row, row your boat,',
      'Gently down the stream.',
      'Merrily, merrily, merrily, merrily,',
      'Life is but a dream!',
    ],
  },
];

export const CVC_FAMILIES = [
  // ── A vowel families ──────────────────────────────
  {
    id: 'at',
    family: '-at',
    color: '#FF6B8A',
    free: true,
    words: [
      { word: 'cat', emoji: '🐱' },
      { word: 'bat', emoji: '🦇' },
      { word: 'hat', emoji: '🎩' },
      { word: 'rat', emoji: '🐭' },
      { word: 'sat', emoji: '🪑' },
    ],
  },
  {
    id: 'ad',
    family: '-ad',
    color: '#FF9F43',
    free: false,
    words: [
      { word: 'bad', emoji: '😠' },
      { word: 'dad', emoji: '👨' },
      { word: 'had', emoji: '🤲' },
      { word: 'mad', emoji: '😡' },
      { word: 'sad', emoji: '😢' },
    ],
  },
  {
    id: 'ag',
    family: '-ag',
    color: '#B57BFF',
    free: false,
    words: [
      { word: 'bag', emoji: '👜' },
      { word: 'tag', emoji: '🏷️' },
      { word: 'rag', emoji: '🧹' },
      { word: 'wag', emoji: '🐕' },
    ],
  },
  {
    id: 'am',
    family: '-am',
    color: '#FF6B8A',
    free: false,
    words: [
      { word: 'ham', emoji: '🍖' },
      { word: 'jam', emoji: '🍓' },
      { word: 'ram', emoji: '🐏' },
      { word: 'yam', emoji: '🍠' },
    ],
  },
  {
    id: 'an',
    family: '-an',
    color: '#4DAAFF',
    free: false,
    words: [
      { word: 'can', emoji: '🥫' },
      { word: 'fan', emoji: '🌀' },
      { word: 'man', emoji: '🧑' },
      { word: 'pan', emoji: '🍳' },
      { word: 'ran', emoji: '🏃' },
      { word: 'van', emoji: '🚐' },
    ],
  },
  {
    id: 'ap',
    family: '-ap',
    color: '#5DD87A',
    free: false,
    words: [
      { word: 'cap', emoji: '🧢' },
      { word: 'map', emoji: '🗺️' },
      { word: 'nap', emoji: '😴' },
      { word: 'tap', emoji: '🚰' },
      { word: 'lap', emoji: '🦵' },
    ],
  },
  // ── I vowel families ──────────────────────────────
  {
    id: 'ig',
    family: '-ig',
    color: '#B57BFF',
    free: false,
    words: [
      { word: 'big', emoji: '🐘' },
      { word: 'dig', emoji: '⛏️' },
      { word: 'fig', emoji: '🌿' },
      { word: 'pig', emoji: '🐷' },
      { word: 'wig', emoji: '👱' },
    ],
  },
  {
    id: 'in',
    family: '-in',
    color: '#FF9F43',
    free: false,
    words: [
      { word: 'bin', emoji: '🗑️' },
      { word: 'fin', emoji: '🐟' },
      { word: 'pin', emoji: '📌' },
      { word: 'tin', emoji: '🥫' },
      { word: 'win', emoji: '🏆' },
    ],
  },
  {
    id: 'it',
    family: '-it',
    color: '#FF6B8A',
    free: false,
    words: [
      { word: 'bit', emoji: '🔩' },
      { word: 'fit', emoji: '💪' },
      { word: 'hit', emoji: '🥊' },
      { word: 'kit', emoji: '🧰' },
      { word: 'sit', emoji: '🪑' },
    ],
  },
  {
    id: 'ip',
    family: '-ip',
    color: '#FFB347',
    free: false,
    words: [
      { word: 'dip', emoji: '🫙' },
      { word: 'hip', emoji: '🕺' },
      { word: 'lip', emoji: '👄' },
      { word: 'rip', emoji: '✂️' },
      { word: 'tip', emoji: '💡' },
    ],
  },
  // ── E vowel families ──────────────────────────────
  {
    id: 'ed',
    family: '-ed',
    color: '#5DD87A',
    free: false,
    words: [
      { word: 'bed', emoji: '🛏️' },
      { word: 'red', emoji: '🔴' },
      { word: 'fed', emoji: '🍼' },
      { word: 'led', emoji: '💡' },
      { word: 'wed', emoji: '💍' },
    ],
  },
  {
    id: 'en',
    family: '-en',
    color: '#4DAAFF',
    free: false,
    words: [
      { word: 'den', emoji: '🏠' },
      { word: 'hen', emoji: '🐔' },
      { word: 'men', emoji: '👬' },
      { word: 'pen', emoji: '✏️' },
      { word: 'ten', emoji: '🔟' },
    ],
  },
  {
    id: 'et',
    family: '-et',
    color: '#B57BFF',
    free: false,
    words: [
      { word: 'bet', emoji: '🎲' },
      { word: 'get', emoji: '🎁' },
      { word: 'jet', emoji: '✈️' },
      { word: 'net', emoji: '🥅' },
      { word: 'pet', emoji: '🐾' },
      { word: 'vet', emoji: '🏥' },
      { word: 'wet', emoji: '💧' },
    ],
  },
  // ── O vowel families ──────────────────────────────
  {
    id: 'og',
    family: '-og',
    color: '#FF9F43',
    free: false,
    words: [
      { word: 'dog', emoji: '🐕' },
      { word: 'fog', emoji: '🌫️' },
      { word: 'hog', emoji: '🐷' },
      { word: 'log', emoji: '🪵' },
      { word: 'bog', emoji: '🌿' },
    ],
  },
  {
    id: 'ot',
    family: '-ot',
    color: '#FF6B8A',
    free: false,
    words: [
      { word: 'cot', emoji: '🛏️' },
      { word: 'dot', emoji: '🔴' },
      { word: 'got', emoji: '🎁' },
      { word: 'hot', emoji: '🔥' },
      { word: 'not', emoji: '🚫' },
      { word: 'pot', emoji: '🍲' },
    ],
  },
  {
    id: 'op',
    family: '-op',
    color: '#4DAAFF',
    free: false,
    words: [
      { word: 'hop', emoji: '🐸' },
      { word: 'mop', emoji: '🧹' },
      { word: 'pop', emoji: '🎈' },
      { word: 'top', emoji: '🪀' },
      { word: 'cop', emoji: '👮' },
    ],
  },
  {
    id: 'ob',
    family: '-ob',
    color: '#FF6B8A',
    free: false,
    words: [
      { word: 'bob', emoji: '🎣' },
      { word: 'job', emoji: '💼' },
      { word: 'mob', emoji: '👥' },
      { word: 'rob', emoji: '🦹' },
    ],
  },
  // ── U vowel families ──────────────────────────────
  {
    id: 'un',
    family: '-un',
    color: '#FF9F43',
    free: false,
    words: [
      { word: 'bun', emoji: '🍞' },
      { word: 'fun', emoji: '🎉' },
      { word: 'run', emoji: '🏃' },
      { word: 'sun', emoji: '☀️' },
      { word: 'gun', emoji: '🔫' },
    ],
  },
  {
    id: 'ug',
    family: '-ug',
    color: '#5DD87A',
    free: false,
    words: [
      { word: 'bug', emoji: '🐛' },
      { word: 'dug', emoji: '⛏️' },
      { word: 'hug', emoji: '🤗' },
      { word: 'jug', emoji: '🫙' },
      { word: 'mug', emoji: '☕' },
      { word: 'rug', emoji: '🪆' },
    ],
  },
  {
    id: 'ut',
    family: '-ut',
    color: '#B57BFF',
    free: false,
    words: [
      { word: 'but', emoji: '↔️' },
      { word: 'cut', emoji: '✂️' },
      { word: 'gut', emoji: '🫁' },
      { word: 'hut', emoji: '🛖' },
      { word: 'nut', emoji: '🥜' },
      { word: 'rut', emoji: '🛤️' },
    ],
  },
];

export const BADGES = [
  { id: 1, icon: '🌟', name: 'First Star!', desc: 'Learned 1 letter', type: 'letters', req: 1 },
  { id: 2, icon: '🔤', name: 'ABC Starter', desc: 'Learned 5 letters', type: 'letters', req: 5 },
  { id: 3, icon: '📖', name: 'Word Worm', desc: 'Learned 10 letters', type: 'letters', req: 10 },
  { id: 4, icon: '🏆', name: 'Alphabet Hero', desc: 'Learned all 26!', type: 'letters', req: 26 },
  { id: 5, icon: '🎵', name: 'Rhyme Time', desc: 'Read 1 rhyme', type: 'rhymes', req: 1 },
  { id: 6, icon: '🐻', name: 'ReaderBear!', desc: 'Read 3 rhymes', type: 'rhymes', req: 3 },
];